name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - run: go test ./...

  lint:
    name: Lint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - uses: golangci/golangci-lint-action@v2
        with:
          version: v1.45

  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - run: make build
        env:
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}

      - uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: bin
          path: bin
          retention-days: 90
